Refactor pipeline to use S3 bucket storage
Made changes to the pipeline to replace all instances of Jenkins
stashing with an upload to and download from S3 cloud storage instead.

diff --git a/jenkins/JenkinsFile-PyPI-packaging b/jenkins/JenkinsFile-PyPI-packaging
--- a/jenkins/JenkinsFile-PyPI-packaging
+++ b/jenkins/JenkinsFile-PyPI-packaging
@@ -23,6 +23,10 @@ PACKAGE_NAME="apache-tvm"
 CPU_IMAGE = "cpu:${params.TLCPACK_CPU_TAG}"
 AARCH64_IMAGE = "cpu_aarch64:${params.TLCPACK_AARCH64_TAG}"
 
+s3_bucket = "tvm-jenkins-artifacts-prod"
+s3_prefix = "tvm/pypi-packaging/${env.BUILD_NUMBER}"
+jenkins_scripts_root = "ci/scripts/jenkins"
+
 
 def cleanup_docker_image(image_type) {
     // Delete images created/tagged by previous steps.
@@ -50,12 +54,70 @@ def clone_tvm() {
 }
 
 
+def upload_s3_stash(stash_name) {
+    sh(
+        script: """
+            ./${jenkins_scripts_root}/s3.py \
+              --action upload \
+              --bucket ${s3_bucket} \
+              --prefix ${s3_prefix}/${stash_name} \
+              --items ${stash_name}.tar.gz
+
+            if [ "\$?" -eq 0 ]; then
+                printf "INFO: files were stashed with the name '%s'.\n", ${stash_name}
+            else
+                printf "WARN: 0 files were specified for the stash.\n"
+                exit 1
+            fi
+        """,
+        label: 'Upload artefacts to S3',
+    )
+}
+
+
+def download_s3_stash(stash_name) {
+    sh(
+        script: """
+            ./${jenkins_scripts_root}/s3.py \
+              --action download \
+              --bucket ${s3_bucket} \
+              --prefix ${s3_prefix}/${stash_name}
+
+            if [ "\$?" -eq 0 ]; then
+                printf "INFO: stash '%s' download complete.\n", ${stash_name}
+            else
+                printf "Error: unable to download stash '%s'.\n", ${stash_name}
+                exit 1
+            fi
+
+        """,
+        label: 'Download artefacts from S3',
+    )
+}
+
+
 def pull_docker_image(image_type) {
     // The tag is expected to be passed as a Jenkins parameter
     sh (
         script: "docker pull tlcpack/package-${image_type}",
         label: "Pull 'package-${image_type}' from Docker Hub",
     )
+}
+
+
+def setup_workspace_from_stash() {
+    clone_tvm()
+    dir("tvm") {
+        download_s3_stash("tvm_workspace")
+    }
+    sh (
+        script: """
+            mv tvm/tvm_workspace.tar.gz . &&
+            rm -rf tvm
+            tar -xvf tvm_workspace.tar.gz
+        """,
+        label: "untar stash 'tvm_workspace'",
+   )
 }
 
 
@@ -164,7 +226,7 @@ pipeline {
 
         stage("Setup workspace") {
             agent {
-                node { label "CPU" }
+                node { label "CPU-SPOT" }
             }
             steps {
                 cleanWs()
@@ -187,11 +249,16 @@ pipeline {
                     } // script
                 } // dir(tvm)
                 sync_package()
-                stash (
-                    includes: "*/**",
-                    name: "tvm_workspace",
-                    allowEmpty: false,
+                sh (
+                    script: """
+                        tar --exclude ./tvm_workspace.tar -cf tvm_workspace.tar . && gzip tvm_workspace.tar
+                        mv tvm_workspace.tar.gz tvm/
+                    """,
+                    label: "Tarball the workspace",
                 )
+                dir("tvm") {
+                    upload_s3_stash("tvm_workspace")
+                }
             }
         } // stage(Setup workspace)
 
@@ -204,21 +271,23 @@ pipeline {
                         expression { return params.BUILD_CPU }
                     }
                     agent {
-                        node { label "CPU" }
+                        node { label "CPU-SPOT" }
                     }
                     steps {
                         cleanWs();
-                        unstash "tvm_workspace"
+                        setup_workspace_from_stash()
                         script {
                             pull_docker_image("${CPU_IMAGE}")
                             build_wheels("${CPU_IMAGE}")
                             cleanup_docker_image("${CPU_IMAGE}")
                         } // script
-                        stash (
-                            includes: "tvm/python/repaired_wheels/**",
-                            name: "tvm_wheels_cpu",
-                            allowEmpty: false,
-                        )
+                        dir("tvm") {
+                            sh (
+                                script: "tar -czf tvm_wheels_cpu.tar.gz python/repaired_wheels",
+                                label: "Tarball the workspace",
+                            )
+                            upload_s3_stash("tvm_wheels_cpu")
+                        }
                     } // steps
                 } // stage(CPU wheel)
 
@@ -228,21 +297,23 @@ pipeline {
                         expression { return params.BUILD_AARCH64 }
                     }
                     agent {
-                        node { label "ARM" }
+                        node { label "ARM-SPOT" }
                     }
                     steps {
                         cleanWs();
-                        unstash "tvm_workspace"
+                        setup_workspace_from_stash()
                         script {
                             pull_docker_image("${AARCH64_IMAGE}")
                             build_wheels("${AARCH64_IMAGE}")
                             cleanup_docker_image("${AARCH64_IMAGE}")
                         } //script
-                        stash (
-                            includes: "tvm/python/repaired_wheels/**",
-                            name: "tvm_wheels_aarch64",
-                            allowEmpty: false,
-                        )
+                        dir("tvm") {
+                            sh (
+                                script: "tar -czf tvm_wheels_aarch64.tar.gz python/repaired_wheels",
+                                label: "Tarball the workspace",
+                            )
+                            upload_s3_stash("tvm_wheels_aarch64")
+                        }
                     } // steps
                 } // stage(arm wheel)
 
@@ -258,12 +329,25 @@ pipeline {
                 }
             }
             agent {
-                node { label "CPU" }
+                node { label "CPU-SPOT" }
             }
             steps {
                 cleanWs();
-                unstash "tvm_wheels_cpu"
-                unstash "tvm_wheels_aarch64"
+                setup_workspace_from_stash()
+                dir("tvm") {
+                    script {
+                        if (params.BUILD_CPU) {
+                            download_s3_stash("tvm_wheels_cpu")
+                            sh "tar -xvf tvm_wheels_cpu.tar.gz --skip-old-files"
+                        }
+                    }
+                    script {
+                        if (params.BUILD_AARCH64) {
+                            download_s3_stash("tvm_wheels_aarch64")
+                            sh "tar -xvf tvm_wheels_aarch64.tar.gz --skip-old-files"
+                        }
+                    }
+                }
                 sh (
                     script: "find . -type f -name *.whl",
                     label: "Find and list wheels",
